services:
  app:
    build:
      context: .
      dockerfile: Dockerfile

    volumes:
      - ..:/workspace:cached

    command: sleep infinity
    depends_on:
      db:
        condition: service_healthy

  db:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile.mysql
    restart: unless-stopped
    tmpfs:
      - /var/lib/mysql
      - /tmp
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: mysqltest
    healthcheck:
      test: ["CMD-SHELL", "mysql --user=root --password=$$MYSQL_ROOT_PASSWORD --execute=\"SELECT 1\" --silent"]
      interval: 5s
      timeout: 5s
      retries: 30
      start_period: 10s
    command:
      - --max-allowed-packet=96M
      - --character-set-server=utf8mb4
      - --disable-log-bin
      - --local-infile=1
      - --max-connections=250
      - --secure-file-priv=/var/tmp
      - --log-bin-trust-function-creators=1
