<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFrameworks>net11.0</TargetFrameworks>
    <ManagePackageVersionsCentrally>false</ManagePackageVersionsCentrally>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="BenchmarkDotNet" Version="0.16.0-preview.1" />
    <!-- <PackageReference Include="MySqlConnector" Version="2.6.1" /> -->
    <PackageReference Include="MySql.Data" Version="26.7.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\MySqlConnector\MySqlConnector.csproj" />
  </ItemGroup>
</Project>
